HeronMkII/obc

.gitignore
build/.gitignore
makefile
manual_tests/commands_test/commands_test.c
manual_tests/commands_test/makefile
manual_tests/makefile
manual_tests/rtc_alarms_test/rtc_alarms_test.c
src/general.c
src/general.h
src/main.c
src/mem.h
src/rtc.h

- Reorganized files in `src` folder
- Updated makefiles and `.gitignore` from `templates` repository
- Removed `build` folder
- Cleaned up duplicated code

Reorganization

---

.gitignore
makefile
manual_tests/makefile

- New `make read-eeprom` command
- Refactoring

Makefile and gitignore updates

---

manual_tests/mem_byte_test/mem_byte_test.c
manual_tests/mem_section_test/mem_section_test.c
src/mem.c
src/mem.h

Refactoring:
- Process of reading/writing EEPROM
- New struct to group memory header data
- New array with all memory section structs
- New function to translate a virtual address to chip number and chip address
- New function to wait for memory to not be busy
- Naming and documentation improvements
- Style guide compliance
Test coverage:
- `mem_byte_test` - test cases for single-byte, multi-byte, erase, pattern, random
- `mem_section_test` - test header and field write/read for all sections, preserving EEPROM between reboots

Memory library - refactoring and test coverage

---

manual_tests/mem_section_test/mem_section_test.c
manual_tests/rtc_alarms_test/rtc_alarms_test.c
manual_tests/rtc_time_test/rtc_time_test.c
src/mem.h
src/rtc.c
src/rtc.h

- Refactored naming, constants, structs, enums
- Used standard lib-common SPI mode functions

RTC review

---

manual_tests/commands_test/commands_test.c
manual_tests/mem_byte_test/mem_byte_test.c
manual_tests/mem_section_test/mem_section_test.c
src/can_commands.c
src/can_commands.h
src/can_interface.c
src/commands.c
src/commands.h
src/general.c
src/mem.c
src/mem.h

Updated the command system and commands test:
- Read/write data from/to memory - new mem functions for blocks
- Use real RTC data
- Add new commands
- Update naming and constants
- Display converted data
- Add more diagnostic and debugging information
- Bug fixes
- Cleanup

Command system - memory, RTC, debugging

---

manual_tests/commands_test/commands_test.c
src/can_commands.c
src/commands.c
src/commands.h
src/general.c

Updates with new functionality in the command system:
- Start a timer that triggers automatic data collection every minute
- Keep track of the currently executing command to ensure command atomicity (they execute one at a time in sequence)
- Renaming and cleanup

Commands - data collection timer, command termination

---

manual_tests/delay_comms_test/delay_comms_test.c
manual_tests/delay_comms_test/makefile
manual_tests/makefile
src/commands.c
src/general.c
src/general.h

- Implemented logic and EEPROM operations to recover state between restarts
- Implemented the framework for delaying before turning on comms

Restart logic - comms delay, restart count, uptime

---

manual_tests/transceiver_uart_test/makefile
manual_tests/transceiver_uart_test/transceiver_uart_test.c
src/transceiver.c
src/transceiver.h

Refactored how the transceiver library processes UART RX to support both transceiver command responses and received messages from the ground station.

Transceiver UART

---

manual_tests/commands_test/commands_test.c
manual_tests/commands_test/makefile
manual_tests/uptime_test/makefile
src/commands.c
src/commands.h
src/general.c

Added switch for simulating local actions without OBC peripherals.

Commands testing update

---

makefile
manual_tests/makefile
manual_tests/mem_section_test/mem_section_test.c
manual_tests/rtc_alarms_test/rtc_alarms_test.c

- Compilation fixes
- Updated makefiles to use the 64M1

New PCB update

---

manual_tests/commands_test/commands_test.c
manual_tests/transceiver_test/makefile
src/can_interface.c
src/commands.c
src/commands.h
src/uptime.c

- Updated lib-common changes (timer, etc.)
- Improved debugging of commands and callbacks
- Working communication with PAY for currently implemented commands

CAN updates

---

manual_tests/i2c_test/i2c_test.c
manual_tests/i2c_test/makefile
src/i2c.c
src/i2c.h

Library for the SPI to I2C bridge IC.

I2C library

---

manual_tests/uptime_test/uptime_test.c
src/uptime.c
src/uptime.h

Refactored uptime library to multiplex callbacks onto 8-bit timer.

Uptime callback refactoring

---

manual_tests/transceiver_uart_test/transceiver_uart_test.c
src/transceiver.c
src/transceiver.h

Refactored transceiver UART RX for command responses and messages

Transceiver UART refactoring

---

manual_tests/transceiver_test/transceiver_test.c
src/transceiver.c
src/transceiver.h

- Fixed transceiver command response clearing bug
- Updated test

Transceiver command fixes

---

manual_tests/commands_test/commands_test.c
src/can_commands.c
src/can_commands.h
src/commands.c
src/commands.h
src/general.c

- Refactored the command system for commands to accept arbitrary input arguments
- Implemented and updated commands according to the ground station to satellite protocol

Command argument refactoring

---

harness_tests/can-commands/main1.c
harness_tests/can-commands/makefile
manual_tests/rtc_alarms_test/rtc_alarms_test.c
src/rtc.c
src/rtc.h

Finished implementing rtc-alarm interrupts.

Rtc interrupt

---

src/can_commands.c
src/can_commands.h
src/commands.c
src/commands.h
src/trans_commands.h

Added obc transceiver command to allow for arbitrary can command and to send back the received message

Can command send

---

manual_tests/transceiver_baud_rate_test/makefile
manual_tests/transceiver_baud_rate_test/transceiver_baud_rate_test.c
src/transceiver.c
src/transceiver.h

Wrote function to fix the baudrate of the transceiver back to 9600 incase it changes and tested.

Transceiver baud rate

---

manual_tests/main_test/main_test.c
manual_tests/transceiver_uart_rx_test/transceiver_uart_rx_test.c
manual_tests/transceiver_uart_tx_test/transceiver_uart_tx_test.c
src/can_commands.c
src/commands.c
src/main.c
src/trans_commands.c
src/trans_commands.h
src/transceiver.c
src/transceiver.h

- Refactored message RX/TX (decoding/encoding) for the new transceiver packet protocol format
- Refactored variable and function naming

Transceiver message refactoring

---

manual_tests/main_test/main_test.c
manual_tests/main_test/makefile
manual_tests/pre_launch_config/makefile
manual_tests/pre_launch_config/pre_launch_config.c
src/antenna.c
src/antenna.h
src/general.h
src/main.c

Also started a pre-launch configuration program.

Dummy startup commands for comms delay and antenna

---

harness_tests/mem/main1.c
src/mem.c
src/mem.h

- Contains tested erase_mem_sector() and erase_mem_block() functions
- Test harness tests for erase functionality written and working

Mem sectors

---

harness_tests/pre_flight_diagnostic/main1.c
harness_tests/pre_flight_diagnostic/makefile

- Tests Flash Memory, EEPROM, and basic RTC functionality. Reference [#151] (https://github.com/HeronMkII/lib-common/issues/151) for more info
- Resolves issue #67

Pre-Flight Diagnostic Test

---

harness_tests/system_diagnostic/main1.c
harness_tests/system_diagnostic/makefile

- Verifies CAN communication and reset functionality between EPS, PAY and OBC

System Diagnostic Test

---

harness_tests/mem/main1.c
manual_tests/mem_section_test/mem_section_test.c
src/command_utilities.c
src/command_utilities.h
src/commands.c
src/mem.c
src/mem.h

Command log implementation to write transceiver commands to flash

Command log

---

manual_tests/antenna_test/antenna_test.c
manual_tests/comms_delay_test/comms_delay_test.c
src/antenna.c
src/antenna.h
src/general.c

Adds timer countdown, blinking LED1 while antenna is waiting to deploy, and manual release override

Antenna warn and release

---

harness_tests/system_diagnostic/main1.c

#112 
- Added heartbeat resets to system diagnostic (i.e. OBC requests PAY/EPS reset and asserts correctness)
- Updated CAN commands to compile with new function names

Heartbeat Reset for System Diagnostic Tests

---

manual_tests/main_test/main_test.c
src/can_commands.c
src/command_utilities.c
src/command_utilities.h
src/commands.c
src/mem.c
src/mem.h
src/transceiver.c
src/transceiver.h

- Removed base-254 encoding, new encoded format with checksum
- Command ID implementation
- More ACK conditions
- Auto enqueued command indicator with command ID

Command refactoring for new packet format

---

harness_tests/mem/main1.c

Finished the TODOs in mem harness test and updated harness test for opcode change in mem.c

Mem test updates
